import type { Movie } from '@/lib/types';
import images from '@/lib/placeholder-images.json';

const posters: Record<string, { imageUrl: string; imageHint: string }> = {};
images.placeholderImages.forEach(img => {
  posters[img.id] = { imageUrl: img.imageUrl, imageHint: img.imageHint };
});

export const movies: Movie[] = [
  {
    id: '1',
    title: 'Cosmic Odyssey',
    posterUrl: posters['m1'].imageUrl,
    posterHint: posters['m1'].imageHint,
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    rating: 8.6,
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    reviews: [
      { author: 'CinemaBlend', rating: 5, text: 'A mind-bending masterpiece of science fiction.' },
      { author: 'Rolling Stone', rating: 4, text: 'Visually stunning and emotionally resonant.' },
    ],
  },
  {
    id: '2',
    title: 'Blade Runner 2049',
    posterUrl: posters['m2'].imageUrl,
    posterHint: posters['m2'].imageHint,
    description: 'A young Blade Runner\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for 30 years.',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    director: 'Denis Villeneuve',
    rating: 8.0,
    genre: ['Sci-Fi', 'Action', 'Mystery'],
    reviews: [
      { author: 'Wired', rating: 5, text: 'A breathtaking, beautiful sequel that expands on the original.' },
      { author: 'The Verge', rating: 5, text: 'An atmospheric triumph.' },
    ],
  },
  {
    id: '3',
    title: 'Jungle Cruise',
    posterUrl: posters['m3'].imageUrl,
    posterHint: posters['m3'].imageHint,
    description: 'Based on Disneyland\'s theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.',
    cast: ['Dwayne Johnson', 'Emily Blunt', 'Edgar Ramírez'],
    director: 'Jaume Collet-Serra',
    rating: 6.6,
    genre: ['Adventure', 'Comedy', 'Family'],
    reviews: [
      { author: 'IGN', rating: 3, text: 'A fun, if forgettable, family adventure.' },
    ],
  },
  {
    id: '4',
    title: 'Knives Out',
    posterUrl: posters['m4'].imageUrl,
    posterHint: posters['m4'].imageHint,
    description: 'A detective investigates the death of a patriarch of an eccentric, combative family.',
    cast: ['Daniel Craig', 'Chris Evans', 'Ana de Armas'],
    director: 'Rian Johnson',
    rating: 7.9,
    genre: ['Mystery', 'Comedy', 'Crime'],
    reviews: [
      { author: 'Variety', rating: 5, text: 'A delightfully modern whodunnit.' },
      { author: 'The Guardian', rating: 4, text: 'Witty, stylish, and thoroughly entertaining.' },
    ],
  },
  {
    id: '5',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    posterUrl: posters['m5'].imageUrl,
    posterHint: posters['m5'].imageHint,
    description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
    director: 'Peter Jackson',
    rating: 8.8,
    genre: ['Fantasy', 'Adventure', 'Action'],
    reviews: [
      { author: 'Empire', rating: 5, text: 'An epic in the truest sense of the word.' },
    ],
  },
  {
    id: '6',
    title: 'Avatar: The Way of Water',
    posterUrl: posters['m6'].imageUrl,
    posterHint: posters['m6'].imageHint,
    description: 'Jake Sully and Ney\'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora.',
    cast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver'],
    director: 'James Cameron',
    rating: 7.7,
    genre: ['Sci-Fi', 'Action', 'Adventure'],
    reviews: [
      { author: 'Total Film', rating: 4, text: 'A stunning visual spectacle that pushes the boundaries of filmmaking.' },
    ],
  },
  {
    id: '7',
    title: 'The Good, the Bad and the Ugly',
    posterUrl: posters['m7'].imageUrl,
    posterHint: posters['m7'].imageHint,
    description: 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
    cast: ['Clint Eastwood', 'Eli Wallach', 'Lee Van Cleef'],
    director: 'Sergio Leone',
    rating: 8.8,
    genre: ['Western'],
    reviews: [
       { author: 'Cahiers du Cinéma', rating: 5, text: 'The definitive spaghetti Western.' },
    ],
  },
  {
    id: '8',
    title: 'La La Land',
    posterUrl: posters['m8'].imageUrl,
    posterHint: posters['m8'].imageHint,
    description: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    cast: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
    director: 'Damien Chazelle',
    rating: 8.0,
    genre: ['Comedy', 'Drama', 'Music'],
    reviews: [
       { author: 'New York Times', rating: 5, text: 'A vibrant and heartfelt musical for the modern age.' },
    ],
  },
  {
    id: '9',
    title: 'Mad Max: Fury Road',
    posterUrl: posters['m13'].imageUrl,
    posterHint: posters['m13'].imageHint,
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    director: 'George Miller',
    rating: 8.1,
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    reviews: [{ author: 'Rotten Tomatoes', rating: 5, text: 'A visceral, visually stunning masterpiece.' }],
  },
  {
    id: '10',
    title: 'The Matrix',
    posterUrl: posters['m14'].imageUrl,
    posterHint: posters['m14'].imageHint,
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    director: 'Lana Wachowski, Lilly Wachowski',
    rating: 8.7,
    genre: ['Action', 'Sci-Fi'],
    reviews: [{ author: 'Roger Ebert', rating: 4, text: 'A visually dazzling and intellectually challenging film.' }],
  },
  {
    id: '11',
    title: 'Edge of Tomorrow',
    posterUrl: posters['m15'].imageUrl,
    posterHint: posters['m15'].imageHint,
    description: 'A soldier fighting aliens gets to relive the same day over and over again, the day restarting every time he dies.',
    cast: ['Tom Cruise', 'Emily Blunt', 'Bill Paxton'],
    director: 'Doug Liman',
    rating: 7.9,
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    reviews: [{ author: 'IGN', rating: 4, text: 'A smart, thrilling, and surprisingly funny sci-fi actioner.' }],
  },
  {
    id: '12',
    title: 'District 9',
    posterUrl: posters['m16'].imageUrl,
    posterHint: posters['m16'].imageHint,
    description: 'An extraterrestrial race forced to live in slum-like conditions on Earth suddenly finds a kindred spirit in a government agent who is exposed to their biotechnology.',
    cast: ['Sharlto Copley', 'David James', 'Jason Cope'],
    director: 'Neill Blomkamp',
    rating: 7.9,
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    reviews: [{ author: 'The Guardian', rating: 5, text: 'A thrilling and thought-provoking sci-fi allegory.' }],
  },
  {
    id: '13',
    title: 'Inception',
    posterUrl: posters['m17'].imageUrl,
    posterHint: posters['m17'].imageHint,
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    director: 'Christopher Nolan',
    rating: 8.8,
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    reviews: [{ author: 'Empire', rating: 5, text: 'A cinematic puzzle box of astounding complexity and beauty.' }],
  },
  {
    id: '14',
    title: 'Dune: Part Two',
    posterUrl: posters['m18'].imageUrl,
    posterHint: posters['m18'].imageHint,
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    director: 'Denis Villeneuve',
    rating: 8.7,
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    reviews: [{ author: 'Variety', rating: 5, text: 'A monumental piece of science fiction filmmaking.' }],
  },
  {
    id: '15',
    title: 'John Wick: Chapter 4',
    posterUrl: posters['m19'].imageUrl,
    posterHint: posters['m19'].imageHint,
    description: 'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.',
    cast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård'],
    director: 'Chad Stahelski',
    rating: 7.8,
    genre: ['Action', 'Crime', 'Thriller'],
    reviews: [{ author: 'Collider', rating: 5, text: 'A breathtaking symphony of action choreography.' }],
  },
  {
    id: '16',
    title: 'Tenet',
    posterUrl: posters['m20'].imageUrl,
    posterHint: posters['m20'].imageHint,
    description: 'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
    cast: ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki'],
    director: 'Christopher Nolan',
    rating: 7.3,
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    reviews: [{ author: 'IndieWire', rating: 4, text: 'A dizzying, high-concept spectacle.' }],
  },
  {
    id: '17',
    title: 'Spider-Man: Across the Spider-Verse',
    posterUrl: posters['m21'].imageUrl,
    posterHint: posters['m21'].imageHint,
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
    director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    rating: 8.6,
    genre: ['Action', 'Animation', 'Adventure'],
    reviews: [{ author: 'The Hollywood Reporter', rating: 5, text: 'A visually stunning and emotionally powerful sequel.' }],
  },
  {
    id: '18',
    title: 'Everything Everywhere All at Once',
    posterUrl: posters['m22'].imageUrl,
    posterHint: posters['m22'].imageHint,
    description: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.',
    cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Stephanie Hsu'],
    director: 'Daniel Kwan, Daniel Scheinert',
    rating: 8.0,
    genre: ['Action', 'Adventure', 'Comedy'],
    reviews: [{ author: 'A.V. Club', rating: 5, text: 'A wildly inventive and deeply moving masterpiece.' }],
  },
  {
    id: '19',
    title: 'Spider-Man: Into the Spider-Verse',
    posterUrl: posters['m23'].imageUrl,
    posterHint: posters['m23'].imageHint,
    description: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld'],
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    rating: 8.4,
    genre: ['Animation', 'Action', 'Adventure'],
    reviews: [{ author: 'IGN', rating: 5, text: 'A groundbreaking and visually spectacular animated film.' }],
  },
  {
    id: '20',
    title: 'Coco',
    posterUrl: posters['m24'].imageUrl,
    posterHint: posters['m24'].imageHint,
    description: 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
    cast: ['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt'],
    director: 'Lee Unkrich, Adrian Molina',
    rating: 8.4,
    genre: ['Animation', 'Adventure', 'Family'],
    reviews: [{ author: 'Roger Ebert', rating: 4, text: 'A beautiful, vibrant celebration of family, music, and memory.' }],
  },
  {
    id: '21',
    title: 'Your Name.',
    posterUrl: posters['m25'].imageUrl,
    posterHint: posters['m25'].imageHint,
    description: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    cast: ['Ryunosuke Kamiki', 'Mone Kamishiraishi', 'Ryo Narita'],
    director: 'Makoto Shinkai',
    rating: 8.4,
    genre: ['Animation', 'Drama', 'Fantasy'],
    reviews: [{ author: 'Empire', rating: 5, text: 'A stunningly animated and emotionally resonant masterpiece.' }],
  },
  {
    id: '22',
    title: 'Klaus',
    posterUrl: posters['m26'].imageUrl,
    posterHint: posters['m26'].imageHint,
    description: 'A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg\'s new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.',
    cast: ['Jason Schwartzman', 'J.K. Simmons', 'Rashida Jones'],
    director: 'Sergio Pablos, Carlos Martínez López',
    rating: 8.1,
    genre: ['Animation', 'Adventure', 'Comedy'],
    reviews: [{ author: 'Variety', rating: 5, text: 'A new holiday classic is born. A beautifully animated and heartwarming story.' }],
  },
  {
    id: '23',
    title: 'The Mitchells vs. the Machines',
    posterUrl: posters['m27'].imageUrl,
    posterHint: posters['m27'].imageHint,
    description: 'A quirky, dysfunctional family\'s road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity\'s unlikeliest last hope.',
    cast: ['Abbi Jacobson', 'Danny McBride', 'Maya Rudolph'],
    director: 'Mike Rianda, Jeff Rowe',
    rating: 7.6,
    genre: ['Animation', 'Adventure', 'Comedy'],
    reviews: [{ author: 'The Hollywood Reporter', rating: 5, text: 'A hilarious and heartfelt adventure with a unique visual style.' }],
  },
  {
    id: '24',
    title: 'Puss in Boots: The Last Wish',
    posterUrl: posters['m28'].imageUrl,
    posterHint: posters['m28'].imageHint,
    description: 'Puss in Boots discovers that his passion for adventure has taken its toll: he has burned through eight of his nine lives. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
    cast: ['Antonio Banderas', 'Salma Hayek', 'Harvey Guillén'],
    director: 'Joel Crawford, Januel Mercado',
    rating: 7.9,
    genre: ['Animation', 'Adventure', 'Comedy'],
    reviews: [{ author: 'Collider', rating: 5, text: 'A surprisingly deep and visually stunning sequel that surpasses the original.' }],
  },
  {
    id: '25',
    title: 'How to Train Your Dragon',
    posterUrl: posters['m29'].imageUrl,
    posterHint: posters['m29'].imageHint,
    description: 'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.',
    cast: ['Jay Baruchel', 'Gerard Butler', 'Craig Ferguson'],
    director: 'Dean DeBlois, Chris Sanders',
    rating: 8.1,
    genre: ['Animation', 'Adventure', 'Family'],
    reviews: [{ author: 'Entertainment Weekly', rating: 5, text: 'A thrilling and heartwarming adventure with breathtaking animation.' }],
  },
  {
    id: '26',
    title: 'Shrek',
    posterUrl: posters['m30'].imageUrl,
    posterHint: posters['m30'].imageHint,
    description: 'A mean lord exiles fairytale creatures into the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.',
    cast: ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz'],
    director: 'Andrew Adamson, Vicky Jenson',
    rating: 7.9,
    genre: ['Animation', 'Adventure', 'Comedy'],
    reviews: [{ author: 'Rolling Stone', rating: 4, text: 'A hilarious and irreverent take on classic fairy tales.' }],
  },
  {
    id: '27',
    title: 'WALL·E',
    posterUrl: posters['m31'].imageUrl,
    posterHint: posters['m31'].imageHint,
    description: 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
    cast: ['Ben Burtt', 'Elissa Knight', 'Jeff Garlin'],
    director: 'Andrew Stanton',
    rating: 8.4,
    genre: ['Animation', 'Adventure', 'Family'],
    reviews: [{ author: 'Time', rating: 5, text: 'A masterpiece of visual storytelling and a poignant commentary on humanity.' }],
  },
  {
    id: '28',
    title: 'Up',
    posterUrl: posters['m32'].imageUrl,
    posterHint: posters['m32'].imageHint,
    description: '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.',
    cast: ['Edward Asner', 'Jordan Nagai', 'John Ratzenberger'],
    director: 'Pete Docter, Bob Peterson',
    rating: 8.2,
    genre: ['Animation', 'Adventure', 'Comedy'],
    reviews: [{ author: 'New York Daily News', rating: 5, text: 'A touching and visually spectacular adventure that soars.' }],
  },
  // Movies for AI recommendation
  {
    id: '100',
    title: 'Movie A',
    posterUrl: posters['m9'].imageUrl,
    posterHint: posters['m9'].imageHint,
    description: 'This is a description for Movie A, a historical drama.',
    cast: ['Actor 1', 'Actor 2'],
    director: 'Director X',
    rating: 7.1,
    genre: ['Drama', 'History'],
    reviews: [],
  },
  {
    id: '101',
    title: 'Movie B',
    posterUrl: posters['m10'].imageUrl,
    posterHint: posters['m10'].imageHint,
    description: 'This is a description for Movie B, a superhero battle.',
    cast: ['Actor 3', 'Actor 4'],
    director: 'Director Y',
    rating: 6.5,
    genre: ['Action', 'Sci-Fi'],
    reviews: [],
  },
  {
    id: '102',
    title: 'Movie C',
    posterUrl: posters['m11'].imageUrl,
    posterHint: posters['m11'].imageHint,
    description: 'This is a description for Movie C, a zombie apocalypse thriller.',
    cast: ['Actor 5', 'Actor 6'],
    director: 'Director Z',
    rating: 7.8,
    genre: ['Horror', 'Thriller'],
    reviews: [],
  },
  {
    id: '103',
    title: 'Movie D',
    posterUrl: posters['m12'].imageUrl,
    posterHint: posters['m12'].imageHint,
    description: 'This is a description for Movie D, a high school comedy.',
    cast: ['Actor 7', 'Actor 8'],
    director: 'Director A',
    rating: 6.2,
    genre: ['Comedy'],
    reviews: [],
  },
  {
    id: '104',
    title: 'Movie E',
    posterUrl: posters['m1'].imageUrl,
    posterHint: 'futuristic adventure',
    description: 'This is a description for Movie E, a futuristic adventure.',
    cast: ['Actor 9', 'Actor 10'],
    director: 'Director B',
    rating: 8.1,
    genre: ['Sci-Fi', 'Adventure'],
    reviews: [],
  },
];

export const getMovies = (query?: string, genre?: string): Movie[] => {
  let filteredMovies = movies;

  if (genre) {
    filteredMovies = filteredMovies.filter(movie => movie.genre.includes(genre));
  }
  
  if (query) {
    const lowerCaseQuery = query.toLowerCase();
    filteredMovies = filteredMovies.filter(
      movie =>
        movie.title.toLowerCase().includes(lowerCaseQuery) ||
        movie.director.toLowerCase().includes(lowerCaseQuery) ||
        movie.cast.some(actor => actor.toLowerCase().includes(lowerCaseQuery))
    );
  }

  // Remove recommendation-only movies from general browsing
  return filteredMovies.filter(movie => !movie.id.startsWith('10'));
};

export const getMovieById = (id: string): Movie | undefined => {
  return movies.find(movie => movie.id === id);
};

export const getMoviesByTitle = (titles: string[]): Movie[] => {
  return movies.filter(movie => titles.includes(movie.title));
}

    